// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/agusheryanto182/go-health-record/module/feature/user (interfaces: UserSvcInterface)

// Package svc is a generated GoMock package.
package svc

import (
	reflect "reflect"

	entities "github.com/agusheryanto182/go-health-record/module/entities"
	dto "github.com/agusheryanto182/go-health-record/module/feature/user/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockUserSvcInterface is a mock of UserSvcInterface interface.
type MockUserSvcInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserSvcInterfaceMockRecorder
}

// MockUserSvcInterfaceMockRecorder is the mock recorder for MockUserSvcInterface.
type MockUserSvcInterfaceMockRecorder struct {
	mock *MockUserSvcInterface
}

// NewMockUserSvcInterface creates a new mock instance.
func NewMockUserSvcInterface(ctrl *gomock.Controller) *MockUserSvcInterface {
	mock := &MockUserSvcInterface{ctrl: ctrl}
	mock.recorder = &MockUserSvcInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSvcInterface) EXPECT() *MockUserSvcInterfaceMockRecorder {
	return m.recorder
}

// CheckUserByIdAndRole mocks base method.
func (m *MockUserSvcInterface) CheckUserByIdAndRole(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserByIdAndRole", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserByIdAndRole indicates an expected call of CheckUserByIdAndRole.
func (mr *MockUserSvcInterfaceMockRecorder) CheckUserByIdAndRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserByIdAndRole", reflect.TypeOf((*MockUserSvcInterface)(nil).CheckUserByIdAndRole), arg0, arg1)
}

// DeleteUserNurse mocks base method.
func (m *MockUserSvcInterface) DeleteUserNurse(arg0 *dto.DeleteUserNurse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserNurse", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserNurse indicates an expected call of DeleteUserNurse.
func (mr *MockUserSvcInterfaceMockRecorder) DeleteUserNurse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserNurse", reflect.TypeOf((*MockUserSvcInterface)(nil).DeleteUserNurse), arg0)
}

// GetUserByFilters mocks base method.
func (m *MockUserSvcInterface) GetUserByFilters(arg0 *dto.UserFilter) ([]*dto.UserFilterResponses, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByFilters", arg0)
	ret0, _ := ret[0].([]*dto.UserFilterResponses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByFilters indicates an expected call of GetUserByFilters.
func (mr *MockUserSvcInterfaceMockRecorder) GetUserByFilters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByFilters", reflect.TypeOf((*MockUserSvcInterface)(nil).GetUserByFilters), arg0)
}

// GetUserByID mocks base method.
func (m *MockUserSvcInterface) GetUserByID(arg0 string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserSvcInterfaceMockRecorder) GetUserByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserSvcInterface)(nil).GetUserByID), arg0)
}

// Login mocks base method.
func (m *MockUserSvcInterface) Login(arg0 *dto.LoginUser) (*dto.RegisterAndLoginUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0)
	ret0, _ := ret[0].(*dto.RegisterAndLoginUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserSvcInterfaceMockRecorder) Login(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserSvcInterface)(nil).Login), arg0)
}

// Register mocks base method.
func (m *MockUserSvcInterface) Register(arg0 *dto.RegisterUser) (*dto.RegisterAndLoginUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(*dto.RegisterAndLoginUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserSvcInterfaceMockRecorder) Register(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserSvcInterface)(nil).Register), arg0)
}

// SetPasswordNurse mocks base method.
func (m *MockUserSvcInterface) SetPasswordNurse(arg0 *dto.SetPasswordNurse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPasswordNurse", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPasswordNurse indicates an expected call of SetPasswordNurse.
func (mr *MockUserSvcInterfaceMockRecorder) SetPasswordNurse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasswordNurse", reflect.TypeOf((*MockUserSvcInterface)(nil).SetPasswordNurse), arg0)
}

// UpdateUserNurse mocks base method.
func (m *MockUserSvcInterface) UpdateUserNurse(arg0 *dto.UpdateUserNurse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserNurse", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserNurse indicates an expected call of UpdateUserNurse.
func (mr *MockUserSvcInterfaceMockRecorder) UpdateUserNurse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserNurse", reflect.TypeOf((*MockUserSvcInterface)(nil).UpdateUserNurse), arg0)
}
